import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TestProvider } from "./provider/TestProvider";
import PermanentSideBar from "./components/PermanentSidebar";
import { ConnectWalletButton } from "./components/ConnectWalletButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <>
            <ConnectWalletButton>
              <PermanentSideBar />
            </ConnectWalletButton>

            <br />
            
          </>
        }
      </body>
    </html>
  );
}
